In [20]:
import pandas as pd
import numpy as np

In [9]:
s = pd.read_csv('2020-06-15-MIT_CovidAnalytics-DELPHI.csv', parse_dates=True)

In [10]:
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85224 entries, 0 to 85223
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   forecast_date    85224 non-null  object
 1   target           85224 non-null  object
 2   target_end_date  85224 non-null  object
 3   location         84000 non-null  object
 4   location_name    85224 non-null  object
 5   type             85224 non-null  object
 6   quantile         81673 non-null  float64
 7   value            84000 non-null  float64
dtypes: float64(2), object(6)
memory usage: 5.2+ MB

In [12]:
s2 = pd.read_csv('2020-06-08-MIT_CovidAnalytics-DELPHI.csv', parse_dates=True)

In [13]:
s2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52416 entries, 0 to 52415
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   forecast_date    52416 non-null  object
 1   target           52416 non-null  object
 2   target_end_date  52416 non-null  object
 3   location         52416 non-null  object
 4   location_name    52416 non-null  object
 5   type             52416 non-null  object
 6   quantile         50232 non-null  float64
 7   value            52416 non-null  float64
dtypes: float64(2), object(6)
memory usage: 3.2+ MB

In [22]:
s[s['value'].isna()]

,forecast_date,target,target_end_date,location,location_name,type,quantile,value
8904,2020-06-15,-1 day ahead cum death,2020-06-14,NaN,New York,point,NaN,NaN
8905,2020-06-15,-1 day ahead cum death,2020-06-14,NaN,New York,quantile,0.010,NaN
8906,2020-06-15,-1 day ahead cum death,2020-06-14,NaN,New York,quantile,0.025,NaN
8907,2020-06-15,-1 day ahead cum death,2020-06-14,NaN,New York,quantile,0.050,NaN
8908,2020-06-15,-1 day ahead cum death,2020-06-14,NaN,New York,quantile,0.100,NaN
...,...,...,...,...,...,...,...,...
10171,2020-06-15,-1 day ahead cum death,2020-06-14,NaN,New Mexico,quantile,0.850,NaN
10172,2020-06-15,-1 day ahead cum death,2020-06-14,NaN,New Mexico,quantile,0.900,NaN
10173,2020-06-15,-1 day ahead cum death,2020-06-14,NaN,New Mexico,quantile,0.950,NaN
10174,2020-06-15,-1 day ahead cum death,2020-06-14,NaN,New Mexico,quantile,0.975,NaN
10175,2020-06-15,-1 day ahead cum death,2020-06-14,NaN,New Mexico,quantile,0.990,NaN